sudo: required
services:
  - docker

before_install:
  - docker build -t timbuckiii/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true timbuckiii/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-504625970126"
  bucket_path: "docker-react" # same as app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY